### ISSUE TITLE
Test failure with current {ompr} version

### ISSUE THREAD

**Issue by dirkschumacher** [otrecoding/OTrecod#9] opened 2022-01-14 08:55 UTC
I sent you an email earlier as I could not find the repository. This is the better place I assume. I understand we all have different schedules and priorities, so don't feel pressured from my side by posting the issue here as well.

I recently rewrote the `MIPModel` in {ompr}, which should be backwards compatible. However I noticed that with the most recent version one of the tests in your package fails:

```
Failure (test-OT-outcome.R:32:3): OT_outcome works
sum(is.na(test1[[8]][, 10])) not equal to 0.
1/1 mismatches
[1] 50 - 0 == 50
```

I looked at the model and it wasn't obvious to me if that is something caused by a bug in `MIPModel` that I newly introduced or by a bug that has been fixed (or something else). In any case, it would be great if we can investigate that before a new version of {ompr} arrives on CRAN. If there is anything I can help with, please let me know.

In order to install the latest {ompr} version you can use `remotes::install_github("dirkschumacher/ompr")`

**Comment by gguernec** [comment] 2022-01-14 15:15
Hello, 

Sorry for my delayed answer :/

Following your last email, I am currently looking to resolve the issue. 
At first glance, it would seem that the new version fo the MIPModel function, integrated in our functions OT_joint and OT_outcome, still provides good solutions to our optimization systems  which is a rather good news for you but not so good for me ..., 

I would currently lean towards a problem in the indiv_grp_closest () function from OTrecod.
I will continue to investigate and tell you more next week.

thank you for your understanding,


Gregory Guernec

**Comment by gguernec** [comment] 2022-01-17 15:52
Hello Dirk,


I think I have found the origin of the problem: it concerns the output of the new version of the ompr::solution function which provides identical estimates, still stored in a solution vector, but it is the ORDER of the solutions in the vector which differs from the previous version.

For example:
Previously with our OT_outcome() function (OTrecod package) on a given example we got the solution using a MIP model:

> solution = ompr::get_solution(result, transport[y,z])
           variable   y   z value
transportation   1   1  0.22248804
transportation   2   1  0.02889318
transportation   3   1  0.00000000
transportation   1   2  0.00000000
transportation   2   2  0.24861878
transportation   3   2  0.00000000
transportation   1   3  0.00000000
transportation   2   3  0.15311005
transportation   3   3  0.09550874
transportation   1   4  0.00000000
transportation   2   4  0.00000000
transportation   3   4  0.25138122

which gave us the following transport matrix using the basic code:

>transportA_val = matrix(solution[,4], ncol = 4, nrow = 3); transportA_val

              [1]            [2]                 [3]            [4]
[1] 0.22248804 0.0000000 0.00000000 0.0000000
[2] 0.02889318 0.2486188 0.15311005 0.0000000
[3] 0.00000000 0.0000000 0.09550874 0.2513812

Now we have, with the new version:

> solution = ompr::get_solution(result, transport[y,z])

        variable     y   z  value
transportation   1  1  0.22248804
transportation   1  2  0.00000000
transportation   1  3  0.00000000
transportation   1  4  0.00000000
transportation   2  1  0.02889318
transportation   2  2  0.24861878
transportation   2  3  0.15311005
transportation   2  4  0.00000000
transportation   3  1  0.00000000
transportation   3  2  0.00000000
transportation   3  3  0.09550874
transportation   3  4  0.25138122

The solution is the same, but the new order gives us  now a wrong transport matrix following the same instruction:
>transportA_val = matrix(solution[,4], ncol = 4, nrow = 3); transportA_val

              [1]            [2]                 [3]            [4]
[1] 0.222488 0.00000000 0.15311 0.00000000
[2] 0.000000 0.02889318 0.00000 0.09550874
[3] 0.000000 0.24861878 0.00000 0.25138122

... same solutions but different values'order.

So, in this way, could you please change the order of the outputs of the ompr::solution() function to guarantee the same order of solutions as before?

I think it is the main problem ...


thank you in advance


Gregory Guernec

**Comment by dirkschumacher** [comment] 2022-01-17 16:14
Thanks for looking into that. I think it would be better to not assume that the data.frame is ordered in a particular way, and to always sort it yourself. As you already have dplyr as a dependency, maybe just use e.g. `arrange(solution, y, z)` to have a stable ordering. Would that be possible?

I'd rather not want to give guarantees on ordering.

**Comment by dirkschumacher** [comment] 2022-01-17 17:36
BTW, when running the test with GLPK logs on, the problem is reported as being unbounded:
```
<SOLVER MSG>  ----
GLPK Simplex Optimizer, v4.65
28 rows, 31 columns, 86 non-zeros
      0: obj =   0.000000000e+00 inf =   2.000e+00 (8)
      7: obj =   4.144554724e+00 inf =   5.551e-17 (0)
*     9: obj =   4.144554724e+00 inf =   2.776e-17 (14)
LP HAS UNBOUNDED PRIMAL SOLUTION
<!SOLVER MSG> ----
Called from: OT_outcome(simu_dat, quanti = c(3, 8), nominal = c(1, 4:5, 7), 
    ordinal = c(2, 6), dist.choice = "M", percent.knn = 0.9, 
    maxrelax = 0, indiv.method = "sequential")
```
Also with the current CRAN version. Is that correct?

**Comment by dirkschumacher** [comment] 2022-01-17 17:38
Also, I tried to restore the original ordering, but it is not possible as it depends on the way `add_variables` is called, including the indexes. Which is not under my control. It was actually a bug in the CRAN version that the ordering is the way it is.

**Comment by pnavaro** [comment] 2022-01-18 10:20
> BTW, when running the test with GLPK logs on, the problem is reported as being unbounded:
> 
> ```
> <SOLVER MSG>  ----
> GLPK Simplex Optimizer, v4.65
> 28 rows, 31 columns, 86 non-zeros
>       0: obj =   0.000000000e+00 inf =   2.000e+00 (8)
>       7: obj =   4.144554724e+00 inf =   5.551e-17 (0)
> *     9: obj =   4.144554724e+00 inf =   2.776e-17 (14)
> LP HAS UNBOUNDED PRIMAL SOLUTION
> <!SOLVER MSG> ----
> Called from: OT_outcome(simu_dat, quanti = c(3, 8), nominal = c(1, 4:5, 7), 
>     ordinal = c(2, 6), dist.choice = "M", percent.knn = 0.9, 
>     maxrelax = 0, indiv.method = "sequential")
> ```
> 
> Also with the current CRAN version. Is that correct?

Hi Dirk, I try your test and I can't reproduce the error you get

[test-outcome.log](https://github.com/otrecoding/OTrecod/files/7888169/test-outcome.log)

**Comment by dirkschumacher** [comment] 2022-01-18 10:44
@pnavaro this is what I get, with a modified version of the package that has `verbose = TRUE` in the `with_ROI(...)` call.
``` r
library(OTrecod)
#> Registered S3 methods overwritten by 'proxy':
#>   method               from    
#>   print.registry_field registry
#>   print.registry_entry registry
# added verbose = TRUE to the solve call in the package
# ompr::solve_model(with_ROI(solver = solvR, verbose = TRUE))
data(simu_data)
simu_dat  = simu_data[c(1:200,301:520),]

## individual method: optimal with 2 databases

# Global
test1 = OT_outcome(simu_dat, quanti = c(3,8), nominal = c(1,4:5,7), ordinal = c(2,6),
                   dist.choice = "M", percent.knn = 0.90, maxrelax = 0,
                   indiv.method = "sequential")
#> ---------------------------------------
#> OT PROCEDURE in progress ...
#> ---------------------------------------
#> Type                     = OUTCOME
#> Distance                 = Manhattan
#> Percent closest knn      = 90%
#> Relaxation parameter     = NO
#> Relaxation value         = 0
#> Individual pred process  = Sequential
#> DB imputed               = BOTH
#> ---------------------------------------
#> <SOLVER MSG>  ----
#> GLPK Simplex Optimizer, v4.65
#> 28 rows, 31 columns, 86 non-zeros
#>       0: obj =   0.000000000e+00 inf =   2.000e+00 (8)
#>       7: obj =   4.144554724e+00 inf =   5.551e-17 (0)
#> *     9: obj =   4.144554724e+00 inf =   2.776e-17 (14)
#> LP HAS UNBOUNDED PRIMAL SOLUTION
#> <!SOLVER MSG> ----
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gguernec** [comment] 2022-01-18 11:43
Hello,


According to the new order of solutions of the ompr::solution function, this problem can be easily handled on our side by changing:

> transportA_val = matrix(solution[,4], length(Y),length(Z))
by:
> transportA_val = matrix(solution[,4], length(Y),length(Z),byrow = TRUE)

in the OT_outcome (and OT_joint) functions. However, it will require an update of our package to CRAN when the update of ompr will be done. The timing does not really suit us because we submitted an article (several weeks ago) to introduce the features of our package and we are still waiting for the feedback from reviewers.


Concerning potential solver problems, verbose = TRUE, is not kept actually as argument of our two functions (verbose = FALSE is actually fixed). When verbose = FALSE, everything seems to work fine, including the modifications previously described on the transport matrices.

Sometimes solving the system can imply critical solutions, it is notably the case here when verbose = TRUE, and I observe now the same warning as you. Nevertheless, I think it is not a problem for our functions because it is not actually established that this option significantly improves the predictions of our models.


Gregory

**Comment by dirkschumacher** [comment] 2022-01-18 12:42
Hi Gregory,

I think the better way would be to not assume a specific sorting of the result and to simply sort the solution (e.g. #10 ). By doing that you would still need to update the CRAN version, but it will work with the old and new ompr version.

Regarding the unbounded LP, I think the problem is that the solution you get is just a partial solution of the simplex algorithm until GLPK could determine the LP is unbounded. See the example below, where the problem is unbounded and you still get a solution back. I would suggest looking at your model again and see if you can add constraints or variable bounds that prevent the unboundedness. E.g. it seems by the name of your variables that all of them are non-negative, so you could add a `lb = 0` bound.

``` r
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)
result <- MIPModel() |> 
  add_variable(x[i,j], i = 1:4, j = 1:4) |>
  set_bounds(x[1, 2], ub = 10) |>
  set_objective(sum_over(x[i, j], i = 1:4, j = 1:2), "max") |> 
  add_constraint(sum_over(x[i, j], i = 1:2) >= 4, j = 1:4) |>
  add_constraint(sum_over(x[i, j], i = 1:4) <= 4, j = 2:4) |>
  solve_model(with_ROI("glpk", verbose = TRUE))
#> <SOLVER MSG>  ----
#> GLPK Simplex Optimizer, v4.65
#> 7 rows, 16 columns, 20 non-zeros
#>       0: obj =   1.000000000e+01 inf =   1.800e+01 (4)
#>       4: obj =   8.000000000e+00 inf =   0.000e+00 (0)
#> LP HAS UNBOUNDED PRIMAL SOLUTION
#> <!SOLVER MSG> ----
solver_status(result)
#> [1] "infeasible"
get_solution(result, x[i, j])
#>    variable i j value
#> 1         x 1 1     4
#> 2         x 1 2     4
#> 3         x 1 3     4
#> 4         x 1 4     4
#> 5         x 2 1     0
#> 6         x 2 2     0
#> 7         x 2 3     0
#> 8         x 2 4     0
#> 9         x 3 1     0
#> 10        x 3 2     0
#> 11        x 3 3     0
#> 12        x 3 4     0
#> 13        x 4 1     0
#> 14        x 4 2     0
#> 15        x 4 3     0
#> 16        x 4 4     0
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gguernec** [comment] 2022-01-19 10:35
Hello,

Thanks a lot Dirk for this important remark !

The unlimited solution problem seems to be solved by adding bounds when the "transport" variable is defined in each optimization system of the OT_outcome function.

Changing:
ompr::add_variable(transport[y,z], y = Y, z = Z, type = "continuous") %>%
by:
ompr::add_variable(transport[y,z], y = Y, z = Z, type = "continuous", lb = 0, ub = 1) %>%

Now we get:
> test1 = OT_outcome(simu_dat, quanti = c(3.8), nominal = c(1.4:5.7), ordinal = c(2.6), dist.choice = "M", percent.knn = 0.90, maxrelax=0,
indiv. method = "sequential")
---------------------------------------
OT PROCEDURE in progress ...
---------------------------------------
Type=OUTCOME
Distance = Manhattan
Percent closest knn = 90%
Relaxation parameter = NO
Relaxation value = 0
Individual pred process = Sequential
DB imputed = BOTH
---------------------------------------

<SOLVERMSG> ----
GLPK Simplex Optimizer, v4.47
28 rows, 31 columns, 86 non-zeros
      0: obj = 0.000000000e+000 infeas = 2.000e+000 (10)
* 7: obj = 4.144554724e+000 infeas = 0.000e+000 (3)
* 29: obj = 3.213626570e+000 infeas = 2.776e-017 (1)
**OPTIMAL SOLUTION FOUND**
<!SOLVER MSG> ----

... And it seems to work fine whatever the example tested in the package.

The updated version of OTrecod will obviously incorporate this change and I also plan to add a warning to the OT_outcome function to warn users when optimal solutions will not be reached by algorithms.

As an idea, maybe the "VERBOSE" argument of a possible future version of the "with_ROI" function could be set to "TRUE" (not "FALSE") as default option to avoid this kind of stressful situations.

Thanks again for your advices,



Gregory

**Comment by dirkschumacher** [comment] 2022-01-19 10:42
I would not use the `verbose = TRUE` option by default, unless users are really interested in that output. You could use the `solver_status` function and issue a warning if the status is not `"optimal"`.

**Comment by dirkschumacher** [comment] 2022-01-20 10:26
Just an update on the status code: `ompr.roi` will map the status code to `success` instead of `optimal` in future versions. So if you want to check the solver status you can use `solver_status(result) %in% c("optimal", "success")`. This will work with both versions.

**Comment by dirkschumacher** [comment] 2022-01-26 12:14
With PR (https://github.com/dirkschumacher/ompr/pull/393) merged, the data.frame gets sorted in reverse order by index for compatibility reasons (so no immediate action required anymore). This will then not cause your test to break on CRAN. I would however encourage to not depend on the ordering in future package versions.

**Comment by gguernec** [comment] 2022-01-26 13:51
Thanks Dirk,
For our functions (Ot_outcome et OT_joint), it was also possible to extract the good order in our transport matrices of interest using i^th and j^th coordinates from the solution object (i and are j are stored in 2 distinct columns).

**Comment by pnavaro** [comment] 2022-07-18 15:48
I close this issue and the PR #10

**Closed by pnavaro** 2022-07-18 15:48 UTC
Labels: bug
